spring:
  datasource:
        url: jdbc:log4jdbc:oracle:thin:@localhost:1521:orcl
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: root
        password: 1234
        

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.project.bit.foo.domain
  configuration:
    mapUnderscoreToCamelCase: true
    
logging:
  file:
    path: logback-spring.xml
